# Generated by Django 6.0.6 on 2026-06-05 21:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profileImage', models.BinaryField(blank=True, help_text='Profilbild als Binärdaten', null=True)),
                ('profileImageContentType', models.CharField(blank=True, help_text='MIME-Type des Profilbilds', max_length=100, null=True)),
                ('user', models.OneToOneField(help_text='Referenzierender Nutzer aus dem Django User Model', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
