"""
Django settings for helloworldpwa project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

def getEnvList(name, default=""):
    return [entry.strip() for entry in os.environ.get(name, default).split(',') if entry.strip()]

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY')
if not SECRET_KEY:
    #raise RuntimeError('DJANGO_SECRET_KEY must be set')
    SECRET_KEY = 'django-insecure-(k604)8no(%@0wm*7mbe5gj972ho%mqk!rzx*g7hwhrifd&#=r'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = str(os.environ.get('DJANGO_DEBUG', 'False')).lower() in ['1', 'true', 'yes']

ALLOWED_HOSTS = getEnvList('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1')
CSRF_TRUSTED_ORIGINS = getEnvList('DJANGO_CSRF_TRUSTED_ORIGINS', 'http://localhost,https://localhost,http://127.0.0.1,https://127.0.0.1')

### Rest Framework - START ###
defaultAuthClasses = ','.join([
    'rest_framework.authentication.BasicAuthentication',
    'rest_framework.authentication.SessionAuthentication',
    'rest_framework.authentication.TokenAuthentication',
])

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': getEnvList('DJANGO_API_AUTH_CLASSES', defaultAuthClasses)
}
#### Rest Framework - ENDE ###


### PWA - START ###

PWA_APP_NAME = 'Hello World PWA'
PWA_APP_SHORT_NAME = 'HWP'
PWA_APP_DESCRIPTION = "Eine Hello World PWA"
PWA_APP_THEME_COLOR = "#8D0000"
PWA_APP_BACKGROUND_COLOR = '#212529'
PWA_APP_DISPLAY = 'standalone'
PWA_APP_SCOPE = '/'
PWA_APP_ORIENTATION = 'any'
PWA_APP_START_URL = '/'
PWA_APP_STATUS_BAR_COLOR = 'default'
PWA_APP_ICONS = [
    {
        'src': '/static/images/favicon.png',
        'sizes': '160x160',
        'type': 'image/png',
    }
]
PWA_APP_ICONS_APPLE = [
    {
        'src': '/static/images/favicon.png',
        'sizes': '160x160',
        'type': 'image/png',
    }
]
PWA_APP_SPLASH_SCREEN = [
    {
        'src': '/static/images/favicon.png',
        'media': '(device-width: 320px) and (device-height: 568px) and (-webkit-device-pixel-ratio: 2)'
    }
]

PWA_APP_SCREENSHOTS = [
    {
        'src': '/static/images/screenshot_desktop.png',
        'sizes': '1280x720',
        'type': 'image/png',
        'form_factor': 'wide'
    },
    {
        'src': '/static/images/screenshot_mobile.png',
        'sizes': '414x896',
        'type': 'image/png',
        'form_factor': 'narrow'
    }
]

PWA_APP_DIR = 'ltr'
PWA_APP_LANG = 'de-DE'

PWA_SERVICE_WORKER_PATH = os.path.join(BASE_DIR, 'web\static\pwa\serviceworker.js')

### PWA - ENDE ###



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Weitere Apps

    # Authentifizierung
    'accounts',
    # Django Restframework
    'rest_framework',
    'rest_framework.authtoken',
    # PWA Section
    'pwa',
    # Web Darstellung
    'web',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'helloworldpwa.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'web.context_processors.datenbank_processor',
                'web.context_processors.softwarename_processor',
                'web.context_processors.versionnumber_processor',
            ],
        },
    },
]

WSGI_APPLICATION = 'helloworldpwa.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

databaseEngine = os.environ.get('DB_ENGINE', 'sqlite').lower()

if databaseEngine == "mysql":
    DATABASES = {
      'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.environ['DB_DATABASE'],
        'USER': os.environ['DB_USER'],
        'PASSWORD': os.environ['DB_PASSWORD'],
        'HOST': os.environ['DB_HOST'],
        'PORT': os.environ.get('DB_PORT', '3306'),
    }
}
else:

    DATABASES = {
        'default': {
        'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }



# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'de-DE'

TIME_ZONE = 'Europe/Berlin'

USE_I18N = True

USE_L10N = True

USE_TZ = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'  # URL für statische Dateien
STATIC_ROOT = BASE_DIR / 'static'  # Zielverzeichnis für gesammelte statische Dateien

# STATICFILES_DIRS ist normalerweise leer, wenn du nur die static Dateien der Apps nutzen möchtest
STATICFILES_DIRS = []

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'